wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: gen_G_loss
      6:
      - 3
      7:
      - 1
    - 1: gen_F_loss
      6:
      - 3
      7:
      - 1
    - 1: cyclic_loss
      6:
      - 3
      7:
      - 1
    - 1: identity_loss
      6:
      - 3
      7:
      - 1
    - 1: disc_X_loss
      6:
      - 3
      7:
      - 1
    - 1: disc_Y_loss
      6:
      - 3
      7:
      - 1
    - 1: total_gen_G_loss
      6:
      - 3
      7:
      - 1
    - 1: total_gen_F_loss
      6:
      - 3
      7:
      - 1
    python_version: 3.8.10
    start_time: 1660402189
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 7
      4: 3.8.10
      5: 0.12.16
      8:
      - 3
      - 5
